name: Build and deploy website

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Install NPM packages
      run: npm ci
    - name: Build website
      run: npm run bundle
    - name: Delete essential files from .gitignore
      run: sed -i '/index.js/d' .gitignore && sed -i '/style.css/d' .gitignore
    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
